apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "blue-green-istio.name" . }}
  labels:
    {{- include "blue-green-istio.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ .Values.virtualService.hosts }}
  gateways:
  - {{ include "blue-green-istio.name" . }}
  http:
  - route:
    - destination:
        host: {{ include "blue-green-istio.name" . }}
      weight: 100